name: CI

on:
  - push
  - pull_request

jobs:
  Ameba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.7.2

      - name: Format
        run: crystal tool format --check

      - name: Install shards
        run: shards install

      - name: Run ameba linter
        run: ./bin/ameba

  Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        crystal_version:
          - latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}

      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards install

      - name: Run tests
        run: crystal spec